# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Markdown

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/markdown.yml'
      - '**.md'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/markdown.yml'
      - '**.md'
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  links:
    name: Links
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: lycheeverse/lychee-action@v1
        with:
          output: '${{ runner.temp }}/lychee/out.md'
          fail: true
